api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    graphql:
        enabled: true
        default_ide: 'graphql-playground'
        graphiql: 
            enabled: true
        graphql_playground:
            enabled: true
        nesting_separator: _
        collection:
            pagination:
                enabled: true
    formats:
        jsonld:
            mime_types: ['application/ld+json']

        json:
            mime_types: ['application/json']

        html:
            mime_types: ['text/html']
    collection:
        pagination:
            enabled: false
            items_per_page: 10
            client_enabled: true
            client_items_per_page: true

