easy_admin:
    entities:
        Jeuxvideo:
            # ...
            list:
                fields:
                    #- { property: 'image', type: 'vich_file', base_path: '%app.path.jeuxvideo_images%', template: 'vich_uploader_image.html.twig' }
                    - { property: 'coverImage', type: 'vich_file', base_path: '%app.path.jeuxvideo_images%', template: 'home/index.html.twig' }
                    
            # ...
            show:
                fields:
                    #- { property: 'image', type: 'vich_file', base_path: '%app.path.jeuxvideo_images%', template: 'vich_uploader_image.html.twig' }
                    - { property: 'coverImage', type: 'vich_file', base_path: '%app.path.jeuxvideo_images%', template: 'home/index.html.twig' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
        
        Categorie:
            # ...
            list:
                fields:
                    #- { property: 'image', type: 'vich_file', base_path: '%app.path.jeuxvideo_images%', template: 'vich_uploader_image.html.twig' }
                    - { property: 'image', type: 'vich_file', base_path: '%app.path.categorie_images%', template: 'home/index.html.twig' }
                    
            # ...
            show:
                fields:
                    #- { property: 'image', type: 'vich_file', base_path: '%app.path.jeuxvideo_images%', template: 'vich_uploader_image.html.twig' }
                    - { property: 'image', type: 'vich_file', base_path: '%app.path.categorie_images%', template: 'home/index.html.twig' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }

        User:
            # ...
            list:
                fields:
                    #- { property: 'image', type: 'vich_file', base_path: '%app.path.jeuxvideo_images%', template: 'vich_uploader_image.html.twig' }
                    - { property: 'avatar', type: 'vich_file', base_path: '%app.path.user_images%', template: 'home/index.html.twig' }
                    
            # ...
            show:
                fields:
                    #- { property: 'image', type: 'vich_file', base_path: '%app.path.jeuxvideo_images%', template: 'vich_uploader_image.html.twig' }
                    - { property: 'avatar', type: 'vich_file', base_path: '%app.path.user_images%', template: 'home/index.html.twig' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
    
    design:
        assets:
            css:
                - './assets/plugins/fontawesome-free/css/all.min.css'
                - 'https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css'
                - './assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'
                - './assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css'

                - './assets/plugins/jqvmap/jqvmap.min.css'

                - './assets/dist/css/adminlte.min.css'

                - './assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'

                - './assets/plugins/daterangepicker/daterangepicker.css'

                - './assets/plugins/summernote/summernote-bs4.min.css'
            js:
                - './assets/plugins/jquery/jquery.min.js'

                - './assets/plugins/jquery-ui/jquery-ui.min.js'

                - './assets/plugins/bootstrap/js/bootstrap.bundle.min.js'

                - './assets/plugins/chart.js/Chart.min.js'

                - './assets/plugins/sparklines/sparkline.js'

                - './assets/plugins/jqvmap/jquery.vmap.min.js'

                - './assets/plugins/jqvmap/maps/jquery.vmap.usa.js'

                - './assets/plugins/jquery-knob/jquery.knob.min.js'

                - './assets/plugins/moment/moment.min.js'

                - './assets/plugins/daterangepicker/daterangepicker.js'

                - './assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js'

                - './assets/plugins/summernote/summernote-bs4.min.js'

                - './assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js'

                - './assets/dist/js/adminlte.js'

                - './assets/dist/js/demo.js'

                - './assets/dist/js/pages/dashboard.js'
