vich_uploader:
    db_driver: orm

    mappings:
        jeuxvideo_images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        categorie_images:
            uri_prefix: /uploads/categories
            upload_destination: '%kernel.project_dir%/public/uploads/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        user_images:
            uri_prefix: /uploads/user
            upload_destination: '%kernel.project_dir%/public/uploads/user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            
