vich_uploader:
    db_driver: orm

    mappings:
        jeuxvideo_images:
            uri_prefix: '%app.path.jeuxvideo_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.jeuxvideo_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        categorie_images:
            uri_prefix: '%app.path.categorie_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.categorie_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        user_images:
            uri_prefix: '%app.path.user_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.user_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        carousel_images:
            uri_prefix: '%app.path.jeuxvideo_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.jeuxvideo_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            
