api_platform:
    resource: .
    type: api_platform
    prefix: /api

app_graphiql:
    path: /docs/graphiql
    controller: api_platform.graphql.action.graphiql

graphql_playground:
    path: /docs/graphql_playground
    controller: api_platform.graphql.action.graphql_playground
