
name: 'app'

type: 'php:7.4'

build:
    flavor: 'none'

disk: 128

mounts:
    '/var': { source: local, source_path: var }
    '/public/upload': { source: local, source_path: uploads }


hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)
        (>&2
            php-ext-install redis 5.3.2
            symfony-build
        )
        (>&2
            cd web/js_app
            unset NPM_CONFIG_PREFIX
            export NVM_DIR=${SYMFONY_APP_DIR}/.nvm

            NODE_VERSION=8 yarn-install

            # Setup everything to use the Node installation
            set +x && . "${NVM_DIR}/nvm.sh" use 8 && set -x

            # Starting from here, everything is setup to use Node 8
            yarn build --environment=prod
        )

variables:
    php-ext:
        redis: 5.3.2

runtime:
    extensions:
        - redis

relationships:
    redis: "redis:redis"


web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
            #index: [ index.php ]
            expires: -1
            scripts: true
            allow: true
            rules:
                '\.(gif|jpe?g|png)$':
                    expires: 60
        "/admin":
            expires: 300
            passthru: true
            allow: true
        '/upload':
            root: 'public/upload'
            scripts: false
            allow: true