#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check
    controller: App\Controller\JwtController::index

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
